### Some anonymization methods experimented, see the link below for details

https://mostly.ai/blog/data-anonymization-in-python

In [44]:
import pandas as pd
import random
import string
import numpy as np

# load the data
original_df = pd.read_csv("Customers_data.csv")

# create an imaginary Salary so we also have some numeric column
original_df['Salary'] = np.random.randint(25000, 175000, size=len(original_df))

# since some of the anonymization methods are quite heavy and slow
# we'll try these with a smaller sample
original_df = original_df[0:1000]
original_df

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,Jillian Gordon,"435 Dylan Neck Suite 993\nKleinhaven, CT 37220",juan14@example.net,"Therapist, music",Martin Group,1997-05-07,001-255-863-9630x09647,North Jessicaland,Papua New Guinea,141028
1,James Williams,Unit 4429 Box 5356\nDPO AE 27029,henryjennifer@example.net,Air broker,Parker-Williams,1967-08-29,(651)492-8192,Lake Alexandra,Belize,81153
2,Joshua Carter,"12795 Solis Landing Apt. 269\nTrevorfurt, IN 0...",michael82@example.org,Musician,Roberts-Marquez,2004-10-02,001-271-795-9749x3330,Paulshire,Christmas Island,45017
3,Joe Ferguson,"02444 Anderson Street Suite 139\nLeeville, SD ...",vsullivan@example.org,Electrical engineer,"Matthews, Nash and Cordova",1969-06-23,+1-901-257-9284,Debramouth,Tonga,52150
4,Travis Ramos,"548 Bonilla Extensions\nWest Robertshire, MH 7...",leah21@example.org,Product designer,Martinez-Hernandez,1990-11-07,001-295-478-2537x125,South Ivanmouth,Solomon Islands,81328
...,...,...,...,...,...,...,...,...,...,...
995,Willie White,"09476 Kevin Lights\nSouth Brianshire, NM 12201",jeffrey13@example.com,Artist,"Mcgrath, Estrada and Wood",1964-09-08,(328)785-2007,Port Aaronburgh,Spain,158142
996,Luis Taylor,"5360 John Terrace\nChristophermouth, FM 93725",devinshort@example.net,"Surveyor, quantity",Dominguez-Murphy,2000-03-05,780-935-5650,North Daniel,Saint Martin,139584
997,Kimberly Tran DDS,"81210 Eric Summit\nTiffanystad, MI 59251",martinnicholas@example.com,"Designer, ceramics/pottery","Miller, Martinez and Higgins",1990-10-04,707.949.9603,Patrickshire,Barbados,72778
998,Denise Brewer,"808 Angela Valleys\nLake Edward, UT 48705",vmiller@example.net,Clinical research associate,Stone Group,1966-07-25,+1-492-823-7456x950,Johnsonfurt,Congo,127550
999,Scott Lopez,"625 Adriana Bypass Suite 816\nAvilaport, SC 54764",joshuaking@example.org,"Production designer, theatre/television/film","Brooks, Coleman and Reid",1996-02-17,9614620959,Andrewhaven,Slovakia (Slovak Republic),144687

**Experiment 1: Randomization**

In [45]:
# define function that operates on entire dataframe
def randomize_values(df):
    for column in df.columns:
        if df[column].dtype == 'O': # check if column has object dtype
            df[column] = [''.join(random.choices(string.ascii_letters + string.digits, k=10)) for _ in range(len(df))] # generate a list of random strings
    return df

# apply function to dataframe
df_rand = randomize_values(original_df.copy())

# all values but numeric are now randomized
df_rand

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,b78JwMlUrd,jIxdskqDGl,bSik50iAyb,SdyGBcxCuA,dhWnsVvIlj,ubpVSQ8KHz,urnfhi5OOp,eR5pDFEiS5,uoWdwQb2qP,141028
1,Qk7nO1ct3V,tw6ch3QHSj,GyBCGFnToe,hHaZb9B6nZ,Emut6kOvUH,k1ePrChm8f,fpxvUBw7mY,i89YDPqNK8,VNhnLcm51S,81153
2,vtplf7EJhZ,u9A9D43FhR,DKCV1nFzvG,xWF6UeY8JQ,QF16JWKHeR,TyCAkqI05w,hp8s3bAOWP,pKSjgJNe4u,GkXSxHvItp,45017
3,YUtAx2twJx,n7NJ2zoWTw,CPsF2khVmN,Gk11I2mf15,5DypOioAba,lQPAyRbkHI,5nDkUhfKcG,SIfpcWMj8k,ACbuJTVqwq,52150
4,n0rfwL1l4o,22nGFtUQNm,sSM10nSgqa,EL7RdJhOhh,RjEgO2Uy9a,kamgfiffrH,LQoPU24xLt,bPTnET5Qxd,DyJvs6xjMd,81328
...,...,...,...,...,...,...,...,...,...,...
995,tjnFSYLB8z,MhWqRE97EJ,gjqj7Ghg0H,yDSfu1xBvQ,GechSJANDT,8JHWo7oZy5,NYfoznH1Qr,4MBzyWdVBC,EMD9EXTo2l,158142
996,ND75axOwpl,w3itZojhGI,GWaZi2GiTq,pWUToLOQ9b,AKnggJqpOd,Wp7YAWPBLL,n7E4YEpPeh,8pnRaUgeFw,0DiiSsWaa5,139584
997,6qVjYwchro,T06XaJRGBQ,0xHwRult6L,24xGNxZqBh,4kTXohP9YJ,zcFfyKgQis,ztcRRite3h,v4CADh4DUu,uWmKqKZnW8,72778
998,e4FmMmLWl4,xDhsx3ZUBY,6T9MhSKFCP,IYSFd1jjBp,5TKNMskDdS,Zoey5zXfCs,3wEO7ONXsq,b0FV3ol3cl,gYIgHvSXs5,127550
999,SUdDOJxRT3,mbvjFTKxLf,YqD9HAsx2L,XrPZsUAd3n,16rQIWCejV,AykIxbokdW,XxDCXxB1zB,pqDXOEJxz8,jaqvTVbFGF,144687

In [46]:
# test index to compare the real and randomized data row
selected_index = 567

In [47]:
df_rand.iloc[selected_index].to_frame()

                567
Name     AV3kkRtueY
Address  0dGJPoCOcY
Email    1yCs3e7tsK
Job      0nQmgEmSaz
Company  tkqVN1zNvR
Date     tYvvJGjK9v
Phone    Wr7ODgGzPC
City     QQvyhgEvu7
Country  btYFPDiHSH
Salary        52206

In [48]:
# the original DataFrame should be in a lookup table
# so it would be possible to trace back to the original values as well
# the lookup table should be stored securely though
original_df.iloc[selected_index].to_frame()

                                                       567
Name                                           Brian Craig
Address  55300 Thomas Island Suite 866\nWest Johnny, MH...
Email                       michaelchristensen@example.com
Job                                    Associate Professor
Company                                      Vargas-Nguyen
Date                                            1959-04-15
Phone                                +1-962-665-3098x66494
City                                     West Vincenthaven
Country                                    Solomon Islands
Salary                                               52206

**Experiment 2: Aggregation (summary, simplify, group by data)**

In [49]:
# Anonymize the ages by grouping them into age ranges
bins = [0, 30_000, 50_000, 80_000, 120_000, 200_000]
labels = ['0-30K', '31-50K', '51-80K', '81-120K', '120K+']
df_rand['Salary'] = pd.cut(df_rand['Salary'], bins=bins, labels=labels)

In [50]:
df_rand

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,b78JwMlUrd,jIxdskqDGl,bSik50iAyb,SdyGBcxCuA,dhWnsVvIlj,ubpVSQ8KHz,urnfhi5OOp,eR5pDFEiS5,uoWdwQb2qP,120K+
1,Qk7nO1ct3V,tw6ch3QHSj,GyBCGFnToe,hHaZb9B6nZ,Emut6kOvUH,k1ePrChm8f,fpxvUBw7mY,i89YDPqNK8,VNhnLcm51S,81-120K
2,vtplf7EJhZ,u9A9D43FhR,DKCV1nFzvG,xWF6UeY8JQ,QF16JWKHeR,TyCAkqI05w,hp8s3bAOWP,pKSjgJNe4u,GkXSxHvItp,31-50K
3,YUtAx2twJx,n7NJ2zoWTw,CPsF2khVmN,Gk11I2mf15,5DypOioAba,lQPAyRbkHI,5nDkUhfKcG,SIfpcWMj8k,ACbuJTVqwq,51-80K
4,n0rfwL1l4o,22nGFtUQNm,sSM10nSgqa,EL7RdJhOhh,RjEgO2Uy9a,kamgfiffrH,LQoPU24xLt,bPTnET5Qxd,DyJvs6xjMd,81-120K
...,...,...,...,...,...,...,...,...,...,...
995,tjnFSYLB8z,MhWqRE97EJ,gjqj7Ghg0H,yDSfu1xBvQ,GechSJANDT,8JHWo7oZy5,NYfoznH1Qr,4MBzyWdVBC,EMD9EXTo2l,120K+
996,ND75axOwpl,w3itZojhGI,GWaZi2GiTq,pWUToLOQ9b,AKnggJqpOd,Wp7YAWPBLL,n7E4YEpPeh,8pnRaUgeFw,0DiiSsWaa5,120K+
997,6qVjYwchro,T06XaJRGBQ,0xHwRult6L,24xGNxZqBh,4kTXohP9YJ,zcFfyKgQis,ztcRRite3h,v4CADh4DUu,uWmKqKZnW8,51-80K
998,e4FmMmLWl4,xDhsx3ZUBY,6T9MhSKFCP,IYSFd1jjBp,5TKNMskDdS,Zoey5zXfCs,3wEO7ONXsq,b0FV3ol3cl,gYIgHvSXs5,120K+
999,SUdDOJxRT3,mbvjFTKxLf,YqD9HAsx2L,XrPZsUAd3n,16rQIWCejV,AykIxbokdW,XxDCXxB1zB,pqDXOEJxz8,jaqvTVbFGF,120K+

In [51]:
# as we can see, the exact salaries are no longer in the dataset above
# a salary range is used instead
# this way of course, we lose some information though
# (can be suboptimal for an ML model)
original_df

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,Jillian Gordon,"435 Dylan Neck Suite 993\nKleinhaven, CT 37220",juan14@example.net,"Therapist, music",Martin Group,1997-05-07,001-255-863-9630x09647,North Jessicaland,Papua New Guinea,141028
1,James Williams,Unit 4429 Box 5356\nDPO AE 27029,henryjennifer@example.net,Air broker,Parker-Williams,1967-08-29,(651)492-8192,Lake Alexandra,Belize,81153
2,Joshua Carter,"12795 Solis Landing Apt. 269\nTrevorfurt, IN 0...",michael82@example.org,Musician,Roberts-Marquez,2004-10-02,001-271-795-9749x3330,Paulshire,Christmas Island,45017
3,Joe Ferguson,"02444 Anderson Street Suite 139\nLeeville, SD ...",vsullivan@example.org,Electrical engineer,"Matthews, Nash and Cordova",1969-06-23,+1-901-257-9284,Debramouth,Tonga,52150
4,Travis Ramos,"548 Bonilla Extensions\nWest Robertshire, MH 7...",leah21@example.org,Product designer,Martinez-Hernandez,1990-11-07,001-295-478-2537x125,South Ivanmouth,Solomon Islands,81328
...,...,...,...,...,...,...,...,...,...,...
995,Willie White,"09476 Kevin Lights\nSouth Brianshire, NM 12201",jeffrey13@example.com,Artist,"Mcgrath, Estrada and Wood",1964-09-08,(328)785-2007,Port Aaronburgh,Spain,158142
996,Luis Taylor,"5360 John Terrace\nChristophermouth, FM 93725",devinshort@example.net,"Surveyor, quantity",Dominguez-Murphy,2000-03-05,780-935-5650,North Daniel,Saint Martin,139584
997,Kimberly Tran DDS,"81210 Eric Summit\nTiffanystad, MI 59251",martinnicholas@example.com,"Designer, ceramics/pottery","Miller, Martinez and Higgins",1990-10-04,707.949.9603,Patrickshire,Barbados,72778
998,Denise Brewer,"808 Angela Valleys\nLake Edward, UT 48705",vmiller@example.net,Clinical research associate,Stone Group,1966-07-25,+1-492-823-7456x950,Johnsonfurt,Congo,127550
999,Scott Lopez,"625 Adriana Bypass Suite 816\nAvilaport, SC 54764",joshuaking@example.org,"Production designer, theatre/television/film","Brooks, Coleman and Reid",1996-02-17,9614620959,Andrewhaven,Slovakia (Slovak Republic),144687

**Experiment 3: Masking**

In [52]:
original_df.columns

Index(['Name', 'Address', 'Email', 'Job', 'Company', 'Date', 'Phone', 'City',
       'Country', 'Salary'],
      dtype='object')

In [53]:
# pip install anonymizedf
from anonymizedf.anonymizedf import anonymize

# prepare data for anonymization
an = anonymize(original_df.copy())

# add masked columns
# NOTE! with large complex datasets
# it can take a considerable time to generate these
fake_df = (
    an
    .fake_names("Name", chaining=True)
    .fake_whole_numbers("Salary", chaining=True)
    .fake_names("Address", chaining=True)
    .fake_names("Email", chaining=True)
    .fake_categories("City", chaining=True)
    .fake_categories("Company", chaining=True)
    .fake_categories("Country", chaining=True)
    .fake_categories("Job", chaining=True)
    .fake_dates("Date", chaining=True)
    .fake_names("Phone", chaining=True)
    .show_data_frame()
)

# subset only anonymized columns
# fake_df = fake_df[['Fake_Name', 'Fake_Salary', 'Fake_Age', 'Fake_City', 'Fake_HouseNumber', 'StreetName']]

fake_df.columns

Index(['Name', 'Address', 'Email', 'Job', 'Company', 'Date', 'Phone', 'City',
       'Country', 'Salary', 'Fake_Name', 'Fake_Salary', 'Fake_Address',
       'Fake_Email', 'Fake_City', 'Fake_Company', 'Fake_Country', 'Fake_Job',
       'Fake_Date', 'Fake_Phone'],
      dtype='object')

In [54]:
fake_df[['Fake_Name', 'Fake_Salary', 'Fake_Address',
       'Fake_Email', 'Fake_City', 'Fake_Company', 'Fake_Country', 'Fake_Job',
       'Fake_Date', 'Fake_Phone']]

,Fake_Name,Fake_Salary,Fake_Address,Fake_Email,Fake_City,Fake_Company,Fake_Country,Fake_Job,Fake_Date,Fake_Phone
0,James Howells-Barnes,42003,Mrs Chloe Boyle,Mrs Diana Fox,City 1,Company 1,Country 1,Job 1,1991-08-04,Mr Liam Allen
1,Martin Welch-Crawford,76525,Emma Chamberlain,Frederick Smith-Thompson,City 2,Company 2,Country 2,Job 2,2011-07-17,Terence Martin
2,Leanne Middleton,71861,Melissa Farrell,Alex Baker,City 3,Company 3,Country 3,Job 3,2026-07-24,Miss Gail James
3,Dr Elizabeth Gibson,137202,Lewis Ryan,Heather Williams,City 4,Company 4,Country 4,Job 4,1977-01-15,Keith Smith-Bevan
4,Catherine Hussain,163470,Margaret Howarth-Baker,Chloe Green,City 5,Company 5,Country 5,Job 5,2021-07-14,Hayley Jackson
...,...,...,...,...,...,...,...,...,...,...
995,Kimberley Collins-Barnes,109196,Brett Smith,Mrs Janice Hunt,City 967,Company 976,Country 229,Job 111,1996-05-26,Nicole Clarke
996,Dr Gerard Roberts,125403,Marion Williams,Lesley Pearson,City 968,Company 977,Country 65,Job 245,1984-11-15,Diane Williams
997,Rosie Roberts,155845,Diane Webster,Mr Charlie Ward,City 969,Company 978,Country 205,Job 211,1998-09-24,Harriet Savage
998,Connor Charlton-Woodward,114838,Owen Hartley,Mr Denis Kent,City 970,Company 979,Country 40,Job 322,2006-03-13,Kate Poole
999,Dr Stacey Watson,173973,Julian Cook,Dr Luke Hopkins,City 971,Company 980,Country 189,Job 395,2014-04-28,Dr Kate Pearson

**Experiment 4: Perturbation**

In [55]:
def add_noise(df, column, std = None):
    if std == None:
        std = df[column].std()
    
    withNoise = df[column].add(np.random.normal(0, std, df.shape[0]))
    copy = df.copy()
    copy[column] = withNoise
    return copy


# adds a small noise to Salary so it's not exactly matching with real data
perturbation = add_noise(original_df, 'Salary', std=100)
perturbation

,Name,Address,Email,Job,Company,Date,Phone,City,Country,Salary
0,Jillian Gordon,"435 Dylan Neck Suite 993\nKleinhaven, CT 37220",juan14@example.net,"Therapist, music",Martin Group,1997-05-07,001-255-863-9630x09647,North Jessicaland,Papua New Guinea,141175.832282
1,James Williams,Unit 4429 Box 5356\nDPO AE 27029,henryjennifer@example.net,Air broker,Parker-Williams,1967-08-29,(651)492-8192,Lake Alexandra,Belize,81102.184011
2,Joshua Carter,"12795 Solis Landing Apt. 269\nTrevorfurt, IN 0...",michael82@example.org,Musician,Roberts-Marquez,2004-10-02,001-271-795-9749x3330,Paulshire,Christmas Island,44970.293802
3,Joe Ferguson,"02444 Anderson Street Suite 139\nLeeville, SD ...",vsullivan@example.org,Electrical engineer,"Matthews, Nash and Cordova",1969-06-23,+1-901-257-9284,Debramouth,Tonga,52164.217577
4,Travis Ramos,"548 Bonilla Extensions\nWest Robertshire, MH 7...",leah21@example.org,Product designer,Martinez-Hernandez,1990-11-07,001-295-478-2537x125,South Ivanmouth,Solomon Islands,81286.547031
...,...,...,...,...,...,...,...,...,...,...
995,Willie White,"09476 Kevin Lights\nSouth Brianshire, NM 12201",jeffrey13@example.com,Artist,"Mcgrath, Estrada and Wood",1964-09-08,(328)785-2007,Port Aaronburgh,Spain,158049.756008
996,Luis Taylor,"5360 John Terrace\nChristophermouth, FM 93725",devinshort@example.net,"Surveyor, quantity",Dominguez-Murphy,2000-03-05,780-935-5650,North Daniel,Saint Martin,139629.986006
997,Kimberly Tran DDS,"81210 Eric Summit\nTiffanystad, MI 59251",martinnicholas@example.com,"Designer, ceramics/pottery","Miller, Martinez and Higgins",1990-10-04,707.949.9603,Patrickshire,Barbados,72805.724606
998,Denise Brewer,"808 Angela Valleys\nLake Edward, UT 48705",vmiller@example.net,Clinical research associate,Stone Group,1966-07-25,+1-492-823-7456x950,Johnsonfurt,Congo,127539.579203
999,Scott Lopez,"625 Adriana Bypass Suite 816\nAvilaport, SC 54764",joshuaking@example.org,"Production designer, theatre/television/film","Brooks, Coleman and Reid",1996-02-17,9614620959,Andrewhaven,Slovakia (Slovak Republic),144739.607237